### ISSUE TITLE
Hi, Question for you

### ISSUE THREAD

**Issue by reddye5** [iammrmehedi/msmg-toolkit#1]
Hi,
Thanks for the msmg toolkit upload. Do you happen to know how to create a pack that for msmg toolkit that would install:
https://www.microsoft.com/en-us/download/details.aspx?id=35
into the ISO? I see they have a DirectX 9 driver pack , but not the complete: DirectX End User Runtime. Please let me know. Thanks.

**Comment by iammrmehedi** [comment]
No
