### ISSUE TITLE
getting issues with latest msmg tool kit

### ISSUE THREAD

**Issue by ifelixculpa** [iammrmehedi/msmg-toolkit#2]
Windows version testing on : 22000.778 22H2
Toolkit version : 12.3.7

error image ,please help

![photo_2022-06-28_18-45-46](https://user-images.githubusercontent.com/13099434/176187985-c0cc4afd-2c75-42be-ba86-39896e2cbff0.jpg)

![Screenshot_6](https://user-images.githubusercontent.com/13099434/176187876-2431db2c-d728-449d-9067-136fbecf4777.png)

**Comment by iammrmehedi** [comment]
use the latest verion [Toolkitv12.4.7z](https://github.com/iammrmehedi/msmg-toolkit/blob/main/Toolkit_v12.4.7z)

**Comment by ifelixculpa** [comment]
Used it allready sir, and works flawlessly...thanks a million
