### ISSUE TITLE
Issues hanging up running scripts

### ISSUE THREAD

**Issue by bryanwills** [iammrmehedi/MSMG-Toolkit#5]
After selecting which components to remove for the selected image, upon removal sometimes the removal process will hang unless the spacebar is pressed to continue. This happens when the ISO image is created after customization. Using the spacebar during removal of components when it says press any key to continue, a beep is heard. Any other key does not cause this.

I am using v12.8.7 from the website. I realize that the versions here are older, I wasn't sure where else to report this.

**Comment by iammrmehedi** [comment]
this is not a official repo so thats why the version here is not updated.
