### ISSUE TITLE
stuck integrating windows updates

### ISSUE THREAD

**Issue by vilzio** [iammrmehedi/MSMG-Toolkit#6]
When I try to integrate updates it just gets stuck on processing 1 of 1
![02D6EB61-FFB5-4588-A130-8F942E687B4F](https://user-images.githubusercontent.com/93621816/214198647-24fb1ce7-82bd-4b38-bd8e-06a68cad25a8.jpeg)

Edit: it worked I’m just impatient

**Comment by iammrmehedi** [comment]
ok
